using System.Globalization;
using System.Net;
using System.Text;
using GetJobCV.Modules;

namespace GetJobCV.UI
{
    /// <summary>
    /// Everything an exported report shows: one analysis run.
    /// </summary>
    public sealed record ReportInput(
        string ResumeFileName,
        string JobDescription,
        DateTime GeneratedAt,
        ResumeRecord Record,
        ExperienceSummary Experience,
        IReadOnlyList<ResumeSection> Sections,
        SkillMatcher.SkillReport Skills,
        double Cosine);

    /// <summary>
    /// Writes a report as one self-contained HTML page (no scripts, fonts, or images to
    /// load), which <see cref="ReportPdf"/> prints to the exported PDF. All resume and job
    /// description text is HTML-encoded.
    /// </summary>
    public static class ReportHtml
    {
        public static string Build(ReportInput input)
        {
            ScoreCombiner.CombinedScore combined = ScoreCombiner.Combine(input.Cosine, input.Skills.WeightCoverage);
            string date = input.GeneratedAt.ToString("MMMM d, yyyy 'at' h:mm tt", CultureInfo.InvariantCulture);
            StringBuilder html = new();

            html.Append($"""
                <!doctype html>
                <html lang="en">
                <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>GetJobCV report · {H(input.ResumeFileName)}</title>
                <style>{Css}</style>
                </head>
                <body>
                <main>
                <header class="top">
                  <div class="mark">GetJob<span>CV</span></div>
                  <div class="meta">{H(input.ResumeFileName)} · {H(date)}</div>
                </header>

                """);

            // Score and verdict
            double overall = Math.Clamp(combined.Overall, 0, 1);
            const double Circumference = 2 * Math.PI * 52;
            html.Append($"""
                <section class="card summary">
                  <svg class="ring" viewBox="0 0 120 120" role="img" aria-label="Overall score {Pct(overall)}">
                    <circle cx="60" cy="60" r="52" class="track"/>
                    <circle cx="60" cy="60" r="52" class="arc" stroke-dasharray="{Num(overall * Circumference)} {Num(Circumference)}" transform="rotate(-90 60 60)"/>
                    <text x="60" y="62" class="num">{Pct(overall)}</text>
                    <text x="60" y="82" class="cap">overall</text>
                  </svg>
                  <div>
                    <h1>{H(combined.Verdict)}</h1>
                    <p>{H(ReportText.Advice(input.Skills))}</p>
                  </div>
                </section>

                <section class="card">
                  {Meter("Weighted skill coverage", "Job skills found, weighted by demand and where they appear", input.Skills.WeightCoverage)}
                  {Meter("Text similarity", "Cosine similarity of the two documents' term vectors", input.Cosine)}
                  <p class="note">Overall blends {Pct(ScoreCombiner.DefaultCoverageWeight)} skill coverage with {Pct(ScoreCombiner.DefaultCosineWeight)} text similarity.</p>
                </section>

                <section class="card long">
                  <h2>Skills</h2>
                  <p class="note">Demand is from O*NET. Skills only listed or mentioned count for less than skills shown in use, and nice-to-have skills count half.</p>

                """);
            SkillTable(html, "Matched", "matched", input.Skills.Matched);
            SkillTable(html, "Missing", "missing", input.Skills.Missing);
            SkillTable(html, "Extra", "extra", input.Skills.Extra);
            html.Append("</section>\n\n<section class=\"grid\">\n");

            Candidate(html, input.Record.Contact);
            Experience(html, input.Record.Experience, input.Experience, input.Skills.OverallYears);
            Education(html, input.Record.Education, input.Sections);

            html.Append($"""
                </section>

                <section class="card long">
                  <h2>Job description</h2>
                  <div class="jd">{H(input.JobDescription.Trim())}</div>
                </section>

                <footer>Generated by GetJobCV on {H(date)}. Everything was computed on this computer.</footer>
                </main>
                </body>
                </html>

                """);
            return html.ToString();
        }

        private static string Meter(string name, string description, double value)
        {
            double v = Math.Clamp(value, 0, 1);
            return $"""
                <div class="meter">
                    <div class="row"><h3>{H(name)}</h3><span class="pct">{Pct(v)}</span></div>
                    <p class="note">{H(description)}</p>
                    <div class="bar" role="progressbar" aria-label="{H(name)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{Math.Round(v * 100)}"><span style="width:{Num(v * 100)}%"></span></div>
                  </div>
                """;
        }

        private static void SkillTable(StringBuilder html, string name, string kind, IReadOnlyList<SkillMatcher.ScoredSkill> skills)
        {
            html.Append($"  <h3 class=\"group {kind}\">{name} <span class=\"count\">{skills.Count}</span></h3>\n");
            if (skills.Count == 0)
            {
                html.Append("  <p class=\"note\">None</p>\n");
                return;
            }

            // Same column widths in every group's table so the three line up
            html.Append("  <table>\n    <colgroup><col class=\"c-skill\"><col class=\"c-demand\"><col class=\"c-where\"><col class=\"c-notes\"></colgroup>\n    <thead><tr><th scope=\"col\">Skill</th><th scope=\"col\">Demand</th><th scope=\"col\">In the resume</th><th scope=\"col\">Notes</th></tr></thead>\n    <tbody>\n");
            foreach (SkillMatcher.ScoredSkill skill in skills)
            {
                string demand = skill.Tier switch { 2 => "Hot", 1 => "In demand", _ => "" };
                string notes = string.Join("; ", new[] { ReportText.Years(skill), ReportText.NiceToHave(skill), ReportText.Alternative(skill) }.OfType<string>());
                string evidence = ReportText.Evidence(skill);
                html.Append($"""
                          <tr{(skill.Preferred ? " class=\"nice\"" : "")}><th scope="row">{H(ReportText.DisplayName(skill.Name))}</th><td>{demand}</td><td>{H(char.ToUpperInvariant(evidence[0]) + evidence[1..])}</td><td>{H(notes)}</td></tr>

                    """);
            }
            html.Append("    </tbody>\n  </table>\n");
        }

        private static void Candidate(StringBuilder html, ContactInfo c)
        {
            html.Append($"<div class=\"card\">\n  <h2>Candidate</h2>\n  <p class=\"name\">{H(c.Name ?? "Name not found")}</p>\n  <dl>\n");
            Field("Email", c.Email, null);
            Field("Phone", c.Phone, null);
            Field("GitHub", c.GitHub, c.GitHub);
            Field("LinkedIn", c.LinkedIn, c.LinkedIn);
            html.Append("  </dl>\n</div>\n");

            void Field(string label, string? value, string? url)
            {
                string shown = value is null ? "<span class=\"muted\">—</span>"
                    : url is not null && ReportText.WebUri(url) is { } uri ? $"<a href=\"{H(uri.AbsoluteUri)}\">{H(ReportText.ShortUrl(value))}</a>"
                    : H(value);
                html.Append($"    <dt>{label}</dt><dd>{shown}</dd>\n");
            }
        }

        private static void Experience(StringBuilder html, IReadOnlyList<ExperienceEntry> roles,
            ExperienceSummary summary, SkillMatcher.YearsCheck? required)
        {
            html.Append("<div class=\"card experience\">\n  <h2>Experience</h2>\n");
            if (summary.TotalMonths > 0 || required is not null)
            {
                html.Append($"  <p class=\"strong\">{summary.TotalYears:0.#} years of professional experience</p>\n");
                if (ReportText.OverallYears(required) is { } overall)
                    html.Append($"  <p class=\"{(required!.Credit >= 1.0 ? "ok" : "short")}\">{H(overall)}</p>\n");
            }
            foreach (ExperienceEntry role in roles)
                Entry(html, role.Title ?? role.Organization ?? "Untitled role", ReportText.RoleDetails(role));
            if (roles.Count == 0)
                html.Append("  <p class=\"muted\">No roles found</p>\n");
            if (ReportText.MostTimeWith(summary) is { } mostTime)
                html.Append($"  <p class=\"note\">{H(mostTime)}</p>\n");
            html.Append("</div>\n");
        }

        private static void Education(StringBuilder html, IReadOnlyList<EducationEntry> schools, IReadOnlyList<ResumeSection> sections)
        {
            html.Append("<div class=\"card\">\n  <h2>Education</h2>\n");
            foreach (EducationEntry e in schools)
                Entry(html, e.Degree ?? e.School ?? "Unnamed school", ReportText.SchoolDetails(e));
            if (schools.Count == 0)
                html.Append("  <p class=\"muted\">No schools found</p>\n");

            html.Append("  <h2 class=\"sub\">Sections found</h2>\n");
            html.Append(sections.Count == 0
                ? "  <p class=\"muted\">None</p>\n"
                : $"  <ul class=\"tags\">{string.Concat(sections.Select(s => $"<li>{H(ReportText.SectionName(s))}</li>"))}</ul>\n");
            html.Append("</div>\n");
        }

        private static void Entry(StringBuilder html, string title, string details)
        {
            html.Append($"  <div class=\"entry\"><p class=\"strong\">{H(title)}</p>");
            if (details.Length > 0)
                html.Append($"<p class=\"muted\">{H(details)}</p>");
            html.Append("</div>\n");
        }

        private static string H(string? text) => WebUtility.HtmlEncode(text ?? "");

        private static string Pct(double share) => $"{Math.Round(share * 100).ToString(CultureInfo.InvariantCulture)}%";

        private static string Num(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);

        // Same palette and type as the app. Fonts fall back to ones Windows has.
        private const string Css = """

            :root {
              --bg: #F4F1EA; --surface: #FFFDF8; --ink: #1C1B18; --muted: #5E5A52; --border: #DDD7CB;
              --track: #ECE7DD; --accent: #1F4F8A; --accent-soft: #6E8FB8;
              --matched: #1F4F8A; --missing: #8A3B12; --extra: #3F3B34;
              --display: "Newsreader", Georgia, serif;
              --body: "IBM Plex Sans", "Segoe UI", system-ui, sans-serif;
            }
            * { box-sizing: border-box; }
            body { margin: 0; background: var(--bg); color: var(--ink); font: 15px/1.5 var(--body); }
            main { max-width: 960px; margin: 0 auto; padding: 32px 16px 48px; display: flex; flex-direction: column; gap: 20px; }
            .top { display: flex; justify-content: space-between; align-items: baseline; gap: 16px; flex-wrap: wrap; }
            .mark { font: 600 24px var(--display); }
            .mark span { color: var(--accent); }
            .meta, .note, .muted { color: var(--muted); }
            .note { font-size: 13px; margin: 4px 0 0; }
            .card { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 20px 24px; }
            h1, h2 { font-family: var(--display); margin: 0; }
            h1 { font-size: 26px; line-height: 1.2; }
            h2 { font-size: 20px; }
            h2.sub { font-family: var(--body); font-size: 12px; letter-spacing: .08em; text-transform: uppercase; color: var(--muted); margin-top: 16px; }
            h3 { font-size: 15px; margin: 0; }
            p { margin: 0; }
            .summary { display: flex; align-items: center; gap: 24px; }
            .summary p { color: var(--muted); margin-top: 6px; }
            .ring { width: 124px; height: 124px; flex-shrink: 0; }
            .ring circle { fill: none; stroke-width: 12; }
            .ring .track { stroke: var(--track); }
            .ring .arc { stroke: var(--accent); stroke-linecap: round; }
            .ring text { text-anchor: middle; fill: var(--ink); }
            .ring .num { font: 600 28px var(--display); }
            .ring .cap { font-size: 11px; fill: var(--muted); }
            .meter + .meter { margin-top: 18px; }
            .meter .row { display: flex; justify-content: space-between; gap: 16px; }
            .pct { font-family: "IBM Plex Mono", Consolas, monospace; font-size: 16px; }
            .bar { height: 10px; border-radius: 5px; background: var(--track); margin-top: 8px; overflow: hidden; }
            .bar span { display: block; height: 100%; border-radius: 5px; background: var(--accent); }
            .meter + .meter .bar span { background: var(--accent-soft); }
            .group { margin-top: 20px; padding-bottom: 6px; border-bottom: 2px solid currentColor; }
            .group.matched { color: var(--matched); }
            .group.missing { color: var(--missing); }
            .group.extra { color: var(--extra); }
            .count { font-family: "IBM Plex Mono", Consolas, monospace; color: var(--muted); font-weight: 400; margin-left: 6px; }
            table { width: 100%; border-collapse: collapse; font-size: 14px; margin-top: 4px; table-layout: fixed; }
            .c-skill { width: 22%; } .c-demand { width: 13%; } .c-where { width: 33%; } .c-notes { width: 32%; }
            th, td { text-align: left; padding: 7px 8px 7px 0; border-bottom: 1px solid var(--border); vertical-align: top; }
            thead th { font-size: 12px; color: var(--muted); font-weight: 600; }
            tbody th { font-weight: 600; }
            tr.nice th { font-style: italic; }
            .grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 20px; align-items: start; }
            .grid h2 { font-family: var(--body); font-size: 12px; letter-spacing: .08em; text-transform: uppercase; color: var(--muted); margin-bottom: 10px; }
            .name { font: 600 19px var(--display); margin-bottom: 8px; }
            dl { display: grid; grid-template-columns: auto 1fr; gap: 4px 16px; margin: 0; font-size: 14px; }
            dt { color: var(--muted); }
            dd { margin: 0; overflow-wrap: anywhere; }
            a { color: var(--accent); }
            .strong { font-weight: 600; }
            .ok { color: var(--matched); font-weight: 600; font-size: 13px; }
            .short { color: var(--missing); font-weight: 600; font-size: 13px; }
            .entry { margin-top: 10px; }
            .entry .muted { font-size: 13px; }
            .tags { list-style: none; padding: 0; margin: 0; display: flex; flex-wrap: wrap; gap: 6px; }
            .tags li { background: var(--track); border-radius: 4px; padding: 2px 8px; font-size: 13px; }
            .jd { white-space: pre-wrap; font-size: 14px; margin-top: 10px; }
            footer { color: var(--muted); font-size: 13px; }
            @media screen and (max-width: 760px) { .grid { grid-template-columns: 1fr; } .summary { flex-direction: column; align-items: flex-start; } }
            @media print {
              body { background: #fff; font-size: 12px; }
              main { padding: 0; max-width: none; gap: 14px; }
              .card { break-inside: avoid; border-color: #ccc; padding: 14px 18px; }
              .card.long { break-inside: auto; }
              h2, .group { break-after: avoid; }
              .jd { orphans: 3; widows: 3; }
              /* Three columns are too narrow on paper: Candidate and Education side by side,
                 Experience across the page below them */
              .grid { grid-template-columns: repeat(2, minmax(0, 1fr)); grid-auto-flow: dense; gap: 14px; }
              .grid .experience { grid-column: 1 / -1; }
              thead { display: table-header-group; }
              tr { break-inside: avoid; }
              /* Cards are narrow on paper: labels above values so emails and links don't split */
              dl { grid-template-columns: 1fr; gap: 0; font-size: 12px; }
              dt { font-size: 11px; margin-top: 6px; }
              dd { overflow-wrap: anywhere; }  /* only when a value still doesn't fit */
            }

            """;
    }
}
